---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-java-geyser-pvc
  annotations:
    volumeType: local
    volume.kubernetes.io/selected-node: worker0
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 15Gi
