apiVersion: v1
kind: Secret
metadata:
    name: mc-java-geyser-secrets
    labels:
        role: service-secrets
        app: mc-java-geyser
type: Opaque
stringData:
    #ENC[AES256_GCM,data:LR4yLGmy3ggBf9dJf7op/ncHYdjtKkT2Vewb7impIqOShhYSOJVpRTFlFpd+FhnL,iv:KZEGxWGmC/uOhmw40unRHE7w2iNmebAboewtP18jCAU=,tag:JirE3guLyMElKD+VNhO/Fw==,type:comment]
    #ENC[AES256_GCM,data:SS9lTfMjQMzcATTCriAAPRvQupZk0OqapV3M5YKgVWpNtSXaIxmOtihKe2eIOOtg,iv:RABgCfS6CVWfP7LLVRNowL8UrK5iLNQtGahbcf7ISDA=,tag:bUYNVuaPA5NMlOMcrSesrg==,type:comment]
    #ENC[AES256_GCM,data:lRwCFXeNX0fwG1CIHbXmun7JOGHePvijcels3WC3xF9/1GJrGbejBeR1yPSnz00=,iv:NLYoUBPSdR0lTFj0aLjWgmekbVyM0SFZsT0Q7z0W7Xw=,tag:Mnlk7fE19YxKsFbt+XsUnA==,type:comment]
    #ENC[AES256_GCM,data:EZydoWyp5oVg6bkltlxul4N2e11TD0xR9F0cUbCI8RxUgSiFGVtaDR1cYJwEB4fW7w==,iv:P3d8N5+POIMvE6Fmy7n2AAQbGgCrGlQuMHrf+Ms4ECM=,tag:H8MnEV1Fznv8GkCyax2kyw==,type:comment]
    #ENC[AES256_GCM,data:aO8vx3hBdd0zn2d+/CcQnc7EFe8ancux/K64NxCj28YXWICo89T09hXHmLY=,iv:sH/ozm3AnFUJTa/gklc/fLaT2XfT4r8dhxCNHfRXQO4=,tag:AyeGNNRwaI+jNYAcVG/FpA==,type:comment]
    #ENC[AES256_GCM,data:szHadyNqrkUBfQqmxhXyNpxRO/qrFbznxHBg3NdtRT/SCNzDtTNa7PFEMMm6xDCGfxI=,iv:35glYh6pIfUwRG9P+5DVlDj/61murRCWx3TVogc59jM=,tag:Sq4jeVT414VF+MDZmslVgA==,type:comment]
    WHITELIST: ENC[AES256_GCM,data:E4COERUVPjnRLxH4FVdywcQq6Kz8dbanpfvifhoJq5Z2JoKfydh9sg6r/uIX/3ZMee6sGVBglKtiQs7eMHqthVEqivQz16PEo5XqaFDAETQEzLn7fOJBS3L+lUX2OpvV+klpskJeJ8BIL2V87JpEk3PFa6jppAI4LKl/R+23HZN6zS9yEMeZxZLkntLCUTxNOIYoSIIckBsq/d3kOCW3qt+qeQ18Rf0vS59Pet6FuuTQZbS2yFxbzD6R5XDy5x0JRUydDcsVkW++RlJcTW3FMCxMGq8B7+eizMKF2tw=,iv:7C8AE7Q3AeRoMbN5d0kw/tfiydShW1TFnTZNEg8mAyE=,tag:WwitmXLu6eZFqwX9EVVwfQ==,type:str]
    OPS: ENC[AES256_GCM,data:S10WUeQMhMjVlIAm5ezLO5grj47iTq84rRbUck3uHYTFqLKVYy4gTIqYRyns1VTUAv9K6cSIPKFkMuFuwWCUUuP8JKebTteYew==,iv:HCgokEBZqhTIMRdlcHbiiFoNFie7eSnqmfhqTsoI6Ck=,tag:RF7JP9xYOAT1tA5iU1Y1Ag==,type:str]
sops:
    lastmodified: "2026-04-11T11:23:12Z"
    mac: ENC[AES256_GCM,data:82P6YY7OkX2nPNqdfOFT0szKYzdWyRcxmlPT9tWE0YvoMdPficb+9YoCYF6SpYimoMHX9gMCOHQ70tDt0RPnIDhJlgB1WTagLTiCdZaBqLf//KcWjLv5UiL/RZG/MvErt2deSoz8uE5GmtSs0g4Dr7qq0iNe5Fp7tNxv50fTGb4=,iv:HmA+ljYHU4mQIyYeXzyHw7MwsflPM4kupbglEgQkqS0=,tag:LYAft8KIZbcc8qvvL/iryg==,type:str]
    pgp:
        - created_at: "2026-04-11T11:23:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwSeVs53q4TjAQ/8CI42eqdsL+kVq/6eBGADdz8Il689+7esxzFmM0w+X9X/
            elhkwIYRx/TeCYkIwc2hqSGuBM6/tbDGi47wzqCouIEm1ifdU3e+RckGO330IBam
            5dg9oaIG+0xSmqcHLNopQ48LlE5tgw3J8YwoEEPdtn3IjlQdr87QqtLF2NrsUTgO
            YewvGhltTiLkdhFxLbIe7KZwfg8w+oP7LF2gFUy9Phdt1fjtrJPiegkBSyq8zSXy
            L62Lj22r45s90kMXCXDIwFdtcLUcfuynwBAUijdxZ4MzLNZAd5xGVCO8WP9swPuN
            GalUVKIcT2YnwdOiQj+BpvAXBiE25QK/9p6s5f/QynpQ4lnvVKwHESn0qqu4AP3a
            gHs+5jiShTAftBkkwSNQr3QabJaVMWG5yQ6plmG910fbUD93mGr2YNSvRmVKq1j+
            ecx5NAaGRwYYaEIXxOkF7dIrD4av86Bn22HTnvLGyoanD2XYtEmtbNiDuxqlusTZ
            AfikvFxqvooivxxAN3xhjHjTpFuODdAbC2oSKx+6sSv86umbWvpbqV8P1lhYtvNQ
            NYRPQrYJ/NKE2KPytM+avw9btO8mB19eJGHuUS81qADlkmmZaRjOADXG2GsGaPIf
            6oTLjeU5EMBio1DfOEKi2KejMeAZcmEB597yUrV62F9hMUm1zJIHLeMkonQciHjU
            ZgEJAhDpZqLqLmMK6Ucn04ME5oqSZhcL6IpB3d4KvCNSMXI7BuYEcxgiDMZwyHem
            jfmNqaXhmTBN4OBU9o/KDup41CWOFog/ncF5FONPYGeWJVtUi5I8vRN2hPzMr9f2
            6Cx97WSgNg==
            =olfD
            -----END PGP MESSAGE-----
          fp: EA65B90F135CF8C5E331DA40C87A0BEB390664D3
        - created_at: "2026-04-11T11:23:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D2q685yeOqr8SAQdA1Jr9EQfY8fVOGSYpKhlXS+WuwLsGs4npccSQ4n9yASsw
            AQWQxBY5ssIfv+QNLj7XFkMcRXmD31iOyhcBuCurBbD2GXkI4NKUsC4ZDahlp0qj
            1GYBCQIQK6dVuqJtH7dAtocpH18IO6TlXpD9nGwkelbpoikj5pmD9oonbnfhyMrI
            r/9oOVMcbFpaC7v+Rc3OsfsvtYRFzbtYyAr/fPwVXZ5lVB6CYqp/5fjvVcaTsgaD
            akKCKuMggMs=
            =fGyi
            -----END PGP MESSAGE-----
          fp: D25B7C5D2B5FE33FAB3EBF4BCB6E270ECA40D3A0
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
