apiVersion: v1
kind: Secret
metadata:
    name: mc-java-geyser-secrets
    labels:
        role: service-secrets
        app: mc-java-geyser
type: Opaque
stringData:
    #ENC[AES256_GCM,data:sRhyf4Lz+Fne2CW+YmhaDhLEbSvxhX8UOJBzzSuzR753aDrgp39XSbJFBdjbPIjS,iv:P59tm+rbYLTfnovcN5loX6N4imaH/O57JgDxvNDqJqA=,tag:pilZo9sOZWv15tuItpIV3w==,type:comment]
    #ENC[AES256_GCM,data://idlYoe6byzuLjTOVNBr5bnoIEBRtUKw3MornAlaW66h/KFBAak3C/lGkrtbonn,iv:82B1CHthicXFvf6gqH19rZARbUZQvwDzX3xSgwvrnu4=,tag:KztraJul1bKnuS0enki0Rw==,type:comment]
    #ENC[AES256_GCM,data:MaZNVVwPwdUWi/DIe8+GFwg+c55VJ5l+oL65+9XXFZ+HVzk2xMi+syobYFFUzj4=,iv:KvlgZ3TYAnMejCa93nwk5O8V+MYVFJVER8+STFmTtls=,tag:TcoviUtp/FTIocXsyp1CDg==,type:comment]
    #ENC[AES256_GCM,data:w6Ts1gS0e6QH7JY0fXbZK37KJh1X7zWfo4kh1bRLcIH7WA174J1b6PNe7gqGMtgRBg==,iv:/xzVlhda8ajbU1QCNxqFwEE6bRTxqhibDPRkz/TiM80=,tag:c2masmty1SFE78C6SXdx/Q==,type:comment]
    #ENC[AES256_GCM,data:Gj2hSwzZqCtEl+mJeoS93c33RFDQEBNjJCUEEMC44CvVOSYwRU9IhKw5j/Q=,iv:bpzGr6rOJlWC/vB61Q4Vix+34sl0GhAjPII6PQSobxY=,tag:LAlYv2kuUXzj8ro/MrXPMA==,type:comment]
    #ENC[AES256_GCM,data:7ExbJE1+Z3PN0Yi+ZOlupt5lsP87AZj3C1D4mMDx1VS39N/OSMSWbLNrI+L8xYslyNs=,iv:6MuU7BaIXaEirhjTrYmQCbg3cxAzSMeclJFjg6Garfw=,tag:sRRyE9Xhw5I6FP0D0vS3Bw==,type:comment]
    WHITELIST: ENC[AES256_GCM,data:L3T+nUOPHWJ+vo+eluEUpV717CddQQ4jqrtfIDmystFYcxaN7aCRIOtSpBemDy6mSXL/MEjrhy8nfY0lS7K16WtpFPC1b6WCXK0n455tbiazvzmMAZXZGYpfvHFzl1strt3fF4yAqGfEPdcYdqBcM1rSOS2QrsllO0LyxDwbALmB9aMW4rmCFR6M4GCQAUq6XuqiKPxeGZ8TD0+bVV6JCbyZqfln7hH1Uj7qaH/JGH8Tn11dasOrr/Qzk/oJ7DTEeFom+FzHCqboEeQp4X8BRDG0rOfDB+rRE69URpM=,iv:FiKi85FNZHvYLtD4kP6uMQs9Qm9UX1Rmk8lh2wqDRlk=,tag:QsPYLcqV7rovbdoYbQeMMg==,type:str]
    OPS: ENC[AES256_GCM,data:pclDArYAZtASLaGKGcptdfqaqhCpK+LcvwO18SHpYWUxG2r48JyZKNuMNbsam1ogQiLPphi2t5HedjR/+c+mJGqnMfT8FuajjQ==,iv:xVR34MiB/epOzeXv4puCx0H/A8eWShMflX3ODIsjzAs=,tag:hTnhOJQS1G9XxhUFwDWlAw==,type:str]
sops:
    lastmodified: "2026-02-08T13:12:38Z"
    mac: ENC[AES256_GCM,data:rAGa1J06fB+6ArbvSHuDuMtuugOFFL4b2OB9F2C3Rgd+45OPfU9hxdHAi8w5loUxPwmlLtgBLtp0wKyEpPkbWhZ5aDY0L4N5zKtUmrnXwwTPJyJOnk8JEPCEAmVgHCISbpsPCi7oP4LR0NdMx64pM7Jwc8MUw6kTqqP13bYjcL0=,iv:kGn7ogHeDZIkZD8WR13vN0PG6kkVLmLc4FziV9bNVUI=,tag:ZeyRdG6DtjzLeqExVUVIdA==,type:str]
    pgp:
        - created_at: "2026-02-08T13:12:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwSeVs53q4TjAQ//Q9ozJCgodNa3piMrMj/bwkYKwJhF450H2TopjFN7Jn6F
            siEY+JwuPk+gDJ5KJ0OCELQ9z5YyZcSqO09QNHgcLYCfcyiU7mJqUyYsUwUwF4Xi
            C6tSIs6BpT1yr/RMrNIydv9uOfRccqEQNzkFc4+4Rl9epaECLccqFexwVJHPZXgb
            paVEZ5gV6WEPfp9trAVxdvFeBTt+1IG4R3yaGAAA1rWi+JFMjx+ffiiPD/u4zTMf
            xeAoMhZixSzZFTVR8ukLq5OCCDObDezCjwlqfMb89kdIL8vV1hCTu32Qe+ge1Pmm
            twpmOSeyAgTfNW4gVhxBnMoqGHnUwNn4qsk9DPZ7mL2ROtsoNbDMt8+R+yc5ufx6
            aDwiFWNYklCTDtOzRjDdDj/6rwYrfrseGVIBRSYTC5DOIwhW3UCzzt0zyvAabhzm
            6gXtQ5UljPwK7SLaXG6s3NfRwbA2glqKo+NGc7U2mLWgZpLTHxbjJwxyW+zqN13g
            GTZpBluOsEosOmWvRwfB669eJZZExdMrxKv7gsPZ6WVZmZ7X7xLfjEjuOqzVNt7B
            ff9bg/g3TRPTm5iYZrvw61tPuSgqSKX/xbNwf4d5ZMEh5R2QTuZHjI8Yf0wDVEun
            hf6hXuRYDJb2lEavt1npSF/GCcrQW40NadJzWgmn4Bmn2GOWNX657vtxrbGMppXU
            aAEJAhAplba2y9xnBtFjmFFUnOycE4hQJW9zKsmCpJlEp4cB73SB5NoW7NzL1V2C
            ZlrCqA0xVUY6xGSVtYmR8gkT6zxMv6mV6eymVRIFkD8VBHGYs51jjAI/wHjVvYp3
            TDMiu83shD3n
            =kfzU
            -----END PGP MESSAGE-----
          fp: EA65B90F135CF8C5E331DA40C87A0BEB390664D3
        - created_at: "2026-02-08T13:12:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D2q685yeOqr8SAQdAheuTXiRy1ixBK7uJz9R/g1aPJpJGe53Sq9zi/8IrBF4w
            yU8HF0MuoTqwujkK7KupTuVjn6Mzly6MOxgedwxcR47+3r7IE+d3CPOrgJ2yq2oS
            1GgBCQIQWB4nTHPOFi8sQN8mEsmfLPdYTyiWycGqOi57fbKDPl4YnhMgHP0EvPU8
            lzgzyDDS/z75uIcjPOgOQcF5wQipxPUQVqSog7JDaRmSTI5rH7al/Y+vnUbWXkjd
            ljwuqXfiZuDbjA==
            =Jlw9
            -----END PGP MESSAGE-----
          fp: D25B7C5D2B5FE33FAB3EBF4BCB6E270ECA40D3A0
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
