apiVersion: v1
kind: Secret
metadata:
    name: mc-java-geyser-secrets
    labels:
        role: service-secrets
        app: mc-java-geyser
type: Opaque
stringData:
    WHITELIST: ENC[AES256_GCM,data:yiGmRiOGd/si9wGiUnOLal4NLm+gqwyGLkFsfhEiZeYGBLlJvjwbOj/FrNzlIxAKOxDyxK0Hv6aUeMayF+IN7obASim4zr21Bh8ceZKWcSWcHFbLGZaSiDY0zyAfHaQGB0GVZS5lqY8NVblIeDYAgPkG0K/9+igry9P1IVc52lTluw5aLEdCdQ7YaU/aiIrWkM4CwBL+higLKWvzAFgOccMWymMmYPPLnLt2woWgYeMCgmT6yhGEFQ==,iv:ptMbyoFraV3fj2hwmi1uUCCvTaVIDzIOWo341SInTww=,tag:pNn2H+WjUpvodHenFPIYhw==,type:str]
    OPS: ENC[AES256_GCM,data:G79xukslJxkjI3wol8tIVAnl0T6KRBiQjtPovs5QOqfrObhmUHiA9mGSx32KG6HWJm20MXt/YTB7dqOd9oK962dX0jVxrGWZaw==,iv:3lUrPnQTlhLd+t2g/RM58u51nZiEjFfNVxdxrJdq8l4=,tag:mHTlMwjl2Di3PG8cfhTdew==,type:str]
sops:
    lastmodified: "2026-02-05T12:32:42Z"
    mac: ENC[AES256_GCM,data:0YrtXBLTuWVJA3DdauNpdxiGuGfMDRHNQ3uFPExghbMRj4QDhVmwIzQqyKy+Ew+UjB4hVtEjR8I8lH0PbxjfMuaOXfcqrzzwoasEhn6mBDjDaqsxKm5J2ufR5Hv8B5JHiZsmuKKrqHkq4nRuAYnVvqioAUKhPtyZddoVnB27VrU=,iv:6zYz4g3/2s8F/HQ3LW0kTaouRrDGy567FaqiFdo80cg=,tag:h+fLje9PHactxzqX4beXrw==,type:str]
    pgp:
        - created_at: "2026-02-05T12:32:42Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwSeVs53q4TjAQ/9F/2bnVm9N7tsQqgaEtvfb4828/VHTW8mTxxk5Kxnj/TJ
            IlR96RoWVyhe9otXKX/DCSPbOdZOVCDcpY4B8g/FNva87tzqwIRE0zJkf+mIcxVF
            iEIYrIbAZpPOMR8A1UiEOteB7F9T7y5nJIylSb7ZghMO1XLKw3qDKffuEypjxqn2
            5ki2u/dqE5Z8eA5bD4fyRPuVQF2KBQSV2Acf7tCHjkgWxgT53YmhWqhLSzvrXg4r
            VsBzcUcwD8gnN5wxpfvx772pjvlBcV0zMXgpxB0tXgbeeUjIkiAvz4aiFo6e2DyM
            YSzV1YGET/jnmYx6uKeoubC41SXtLuZXeRheP7zHho23F9Lj0lFfKscS8HUR36kk
            UJldjx9ReQdrL+tH38wy3JXLGSQZ0C9Ql8Yr4ogblU2o8GQqz0rtLxObgua5Qr1d
            PJwc1MbDfSZbnTRhLCrnOVWrU68YdElNk5TUCThhAzFILvOYRmnrNrViwrdmNUOZ
            G3sXMtj2PTjwAitNzN/l4t8N40LYvEorW8rbzkVHDIsjevf7eQCxkLfSdYnafwsc
            ROfkhV1m+cMwp73ozLHx9qn3D867xEKK3TjEDNZnMF7AYfJmWNPO0zUm4DcvN+xJ
            PwFZJAHilqOlg4iqLoiylTtwis1/rSndfbvnxbOb6xb2824PH2Kgo9e8aqTC2VjU
            ZgEJAhA4z3iyRvOmQTTuIlt4ul979VsoUzHFEimjuksx9493aS6e3DBt0T+hWP6G
            iACpTJw+qngLltGOsuJCFy+/kT/4uEeEe1Uv0UYhJmsVBx9byh0oRai1+GqiATHC
            7vKxLxruEA==
            =9UTR
            -----END PGP MESSAGE-----
          fp: EA65B90F135CF8C5E331DA40C87A0BEB390664D3
        - created_at: "2026-02-05T12:32:42Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D2q685yeOqr8SAQdA/VzD/luJBtc1va7R4wxksLt35C+avRd3jEhFdJTUf04w
            6gVJlIgUshrPRbeDja3ZS3AJKdtU2r0yQux+KbFIPfW8RPEpkogqz2Ji+IP3Ywbt
            1GYBCQIQxAng48qMKZvaleyIDQQll33w+KBuR8WxxDELzZzWZHoV5XL4t3R+rkFu
            l/2E4n/DpvybTPIsgzhE8Z7pLZ1xirWLrKmVNP409BZlNlYhUCXN95gNH2AkjyFs
            LOPelOlhcQk=
            =R52X
            -----END PGP MESSAGE-----
          fp: D25B7C5D2B5FE33FAB3EBF4BCB6E270ECA40D3A0
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
