apiVersion: v1
kind: Secret
metadata:
    name: mc-java-geyser-two-secrets
    labels:
        role: service-secrets
        app: mc-java-geyser-two
type: Opaque
stringData:
    #ENC[AES256_GCM,data:quGd8jot2Ye6OWf8N4S69zPC86tV4TwsU34QVz0HMYPESNckB3esC+izTtnXNblv,iv:SzsuCLInHHYPcmI1wKtP4RR6k9AHAt/OusbaaBvnaGQ=,tag:Wo0lLgNwzvhVVP6Us7w/5A==,type:comment]
    #ENC[AES256_GCM,data:hjXkyDYo+4v1jBH8wetkEJ69kSscgAUfFzRyQ86DQo7Ntu+28k+czvXRAWrUTXpE,iv:RqWwoc/PRXZKvQryt4xdjavrA0rmiJtpeOc0c2Q8IWY=,tag:cQOrwfdMnQGW2U4GeGneJw==,type:comment]
    #ENC[AES256_GCM,data:xyj17J+YlA8cQLJlGIHmajDGCAhbJ+tacmIthJ/T22ClNTrEO60e95+sgxRb1Bo=,iv:axaGD4j31ouz60TaKvBmvs90mePXka2+AEkmJdmJXEk=,tag:ZAowN/Cmyd4F/3q6RQ6Uzg==,type:comment]
    #ENC[AES256_GCM,data:Zskdz38Un6xidhDDP3lNyGL6IhaZzBNZzOBBigyJtEUf7KX+mV/9SdwGoXmSSwbGkA==,iv:CIi5ckdlySf6mhiXiPaTGehG2J36b4zfUXllRINQMvA=,tag:OVv/2KQh1VVndfggv9Ji8w==,type:comment]
    #ENC[AES256_GCM,data:I4OMam0oNtRqNtgjCD+a26olZtdhWZjr1KCuo9Rm4v5ZYm84I+LH5mbQtGE=,iv:2G5AkTldBHcS4xVfKIVPJMtxzP2OLr6UuoscuaVg0Yg=,tag:pzzQcwiq7eIH64yoO57L9g==,type:comment]
    #ENC[AES256_GCM,data:VkkQ4G5A3QaW1sifpzHOPmMyS3faYyXxlZSqifNglic6mF4ktum6WBVggj6zr5ZdnkM=,iv:E3W+q0FFmeZXBB3l1TibgPSHAaC6CDRlO5+xRKJkGLM=,tag:KMojEieoY4BzKhOxvZIK9A==,type:comment]
    WHITELIST: ENC[AES256_GCM,data:ze/ntzowqEk/O4VWJbvP5kIF0u1W4gerK4D+AR77L33cvuG/1oWkcWuv0jMDkbErolp1wHiDiNCKSlifDrb5704CSrHFibK40MGxm5R3dz2eRGk0oHmdtJB+tftS+SZY7yjy9UTTIPuMuXs/qNilAIzN2mhteWsbp3NBmUU+x94i04hwx/oES0WGjbXCoX5oK4L5F6xrOM82WiPOAJ4YKJt8EclwM5Tm9X/JnUuRXxqfbCFQiuqbe3azLQ7kP5VZZQSdjJOJ9b6+ikV03HIqdW1EpefVrdasUfLqZaA=,iv:2DYmBQEILyVQ86D9sd7Q89y+79AZs2WAHFb3KL3BoBc=,tag:zki4aYcGK0dAfy/ox+1yaw==,type:str]
    OPS: ENC[AES256_GCM,data:BAtFiMTy8cJbRQR8ZXIm0lphNoLLGaZEZY9NIhKCKSWcEHAOw0FYKuEtl0j7zoDGDY1W0nrl0hiSkzM+1wOK52fFFsqyPYsKqA==,iv:Lh8Y2Jdjjxb72WpKU6nK9Olxa3PUzpIzGl6f46Vlz3c=,tag:Gd+dP7GyQf4zcMNwWxNYCg==,type:str]
sops:
    lastmodified: "2026-02-08T13:12:35Z"
    mac: ENC[AES256_GCM,data:Y0G4y4FU+FbGmHaQavPVgr5vaCdVYX3k/BYM7ZOtGQRm+iUHxPKXhr0HDXKIe4IvWfYzZo2qcD+2l4AGq/jLkZX0fNOEyiqhS6c9wc4OpG9xEJk5Jbr/z6VJhkmJ55tjBnG34U6hTFkv0QUZ9h8Nk540bZnR8utF86Y3e7yojXU=,iv:MRE5ymEaWIDm1ZxkRD2GwtgTEbGOkr0c8bLp1IMLcNE=,tag:spEOOgGVyYPSrmX+lVLlTQ==,type:str]
    pgp:
        - created_at: "2026-02-08T13:12:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwSeVs53q4TjARAAtdztFVngnNIkOkfnTZhBxs5lWuM9IkuFP+uWEqxgWg1a
            HCh/fTaeO5DOHsvNnNbdDKzta44Y9S/On+lcQaYRvjBBW0DnCPXLRNY4ZT9obVYj
            rtJvFUmAKBY1OVVVJYUiBK6wZO8k7j+sWWdabK2iW2Rux3OF78PNmOiUOwsFcDD5
            zuEK1Q788MaZqDZiZ/GRKOV+U1mrm5QqeEpITNsqK9jsZ7MZipJgeBpwOip80MU1
            C3C7Xm5aL+Fc4rDTNLhsr+iudMcuVNHWNMzMaXV+cCfbUgeGJMxUmtnqEIy4+z2M
            IYte+KK7ZvTfa8ph9TB6GR7h3TYXAJFDLjapr1PWmGcHjAH1ZhVsrILcMoWovVvj
            Zs+S9wa38VPagevzNdNwo2UCCN8SSTVxLiOb8VdIKhZX037rc1p9V23ZXVnXKvpK
            OMh3gMrPCOqDIEigIBaVqw4kdEG9tCNoRDc9LcGr+p3LDX1/7qSmoY04UjVdmPxW
            eZg1s519CWELCdWyAg9wzsBAr7ooFyPhBzcz3NHgI5zC3ICT+KlwhWVCVjyEpoqk
            wnAyBgAHAQReAOJZH+2gL/bB7g2YNMSsjQ3Pu95Z54Vrso/cvf0OmUcXcfGKSU8I
            q8TLfaKndey4n1lgdSmu4DVyBuu8HDwDU4B3m11H9SbKpU9seB4IpQTw064grmjU
            aAEJAhCMSZ6fJ1BkVy/HGdY/r6YgcI4gvZYT47b5bS8Z3PZPrJ1hyWq5ug9UHERw
            ajQJVONFjzdE6O/jrye7UX4WGrkOcKCJnRp0Qb9viiM4QwkqnbrZlX8wK/EmH2Jq
            0e3NLAz5qQ3J
            =Lr1h
            -----END PGP MESSAGE-----
          fp: EA65B90F135CF8C5E331DA40C87A0BEB390664D3
        - created_at: "2026-02-08T13:12:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D2q685yeOqr8SAQdADWWDeLljpTcmrkHhGUseJXl8tMaua5fWcwk9bfDfoRsw
            HDVsB+3sQc3tmYYdF1QwkhO+1gouo5dLSpNlEoyJQW3O4CdmikUYzK4wLIuBhMDo
            1GgBCQIQuUP5EjPrP79Rpm75WvNHH9zH/jJu4i6REDtJ7GzoBwKoD4iTYaW6uflZ
            TZvblIeB9aSF9eVDI2vRooL285z/USvbyz4LZWxJ/BpE3WYcN8tJ04bKemYRKP52
            UaRdCwGcl/vTMA==
            =tULe
            -----END PGP MESSAGE-----
          fp: D25B7C5D2B5FE33FAB3EBF4BCB6E270ECA40D3A0
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
