# Repository SOPS configuration, rules on how to encrypt specific files
---
creation_rules:
  - path_regex: cluster-resources/services/.*/.*.yaml
    encrypted_regex: ^(data|stringData)$
    pgp: >-
      EA65B90F135CF8C5E331DA40C87A0BEB390664D3