apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: n8n
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:WWB0CkOkk80LVssLyerJ14POjzhrf/FrQLtP119F3SxbfOC+WFODHFa5hiYk5o9KQ79Yrn/sVB6/VR63AFBPoB5KoclfyhnvctUlyP8FquGUie9qrUPgWABrwMqKkRufPehz3B+WKVdBeYcCNRZ1L/3IKl0tmr8Ea7F/FKkq228=,iv:K82DKJKEe/U0eGPa6SbbTpPsTfO5OgjC4JyKVRbALrU=,tag:QK0nNwF2sPJETYb12DePLg==,type:str]
sops:
    lastmodified: "2026-06-05T11:04:57Z"
    mac: ENC[AES256_GCM,data:V+/ba36YvQqZAdjTR/r5OlswLDkNEIuakL5pamRh3ZH5M5IY6lkljhXxK5oYkbMBL0OpZ9A0yUji4eqaRAoIxWm0ZsOKIGifWvvWo0kvpyEJMoJvYc5xrTODQhN5AAQRk9ESNtCJVHopJiZSnoW7kfziU29+kHn+3EiRZxIgxcU=,iv:Z/qqrGs6dTB7AlgtGfTm++7wDJ7BIJssaJUHjSJYreE=,tag:dqDXKPOR/w3oZPfVLOJEAA==,type:str]
    pgp:
        - created_at: "2026-06-05T11:04:57Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwSeVs53q4TjAQ//TMFahvhL3UUxDTVOxOVAN9zrEvMwYrEwy4TGEXYX9GAG
            hZEvXziSWalN0GJbWqEgl5BJhr4aQhl12eVHNadqHFXdp0YhqqcenDvnOU2+Zp4m
            D74g3oH/eNn4nw5IVhOWw4QnMy+3hvTdzsgt0kzFvh287GojHqsBOI9W2RDF73xz
            NURpFNbM/LTlnFW+8rT0mDHGiWTJFbdkF07vhuTNI3C+AsAIEhf8Wl0SVTMqsP0T
            3HqJbEwE5Ox+mNnwnzJ8M7Ua5gW1K7McdItdjAjiPcAqMrDBQLQKfrrV1ttpzv5b
            fRWjAuFmYVtHU96/UIzbpNwLLpBM/WzjXlzXix+IP7k1aTr4ElCMG5JLTAhCnVqm
            qXFNGAjgFL68da9f7pA6XHfPamoq0rRiFy/mTbxzhDNK1zGi3k6kmOUGDk1Yosrj
            dRpVnnRTlZqNmsG+zuALWPkQT+Hu4tBAzFRGlqUmGtsc2cqf1m9EYPO6ShQVLrGn
            /XhsM0JFG0ZkTns/+gN6HJH8AHX24yci2pMrfLru8paaHwAcWeDqNHTBydU+3hRh
            uoCyXsIZfbBBPOh2+kXB0BGq7ukiN53R6nrcXicDdjhVISwm6H/NHjQC4Oup1y8U
            n0iQRN2cQHaSQcXNuJ/B4uVqqww0Ab5CHaVLPUqJvWf/MSnfWQt/sv93kb8cfQrU
            aAEJAhBiPYFJVlJaAIcDkNp8gN1CtIeprBaD60oYecm9VMm9QtOeHtwywX1bjtAl
            ZmTLI5VGm97A8gf9gxKcFGq8B7LSFljJvo/bDNh+DcBhU7Rq+fvvfbGEXM4lyAyq
            DlEN1ILQ8/s9
            =T2qv
            -----END PGP MESSAGE-----
          fp: EA65B90F135CF8C5E331DA40C87A0BEB390664D3
        - created_at: "2026-06-05T11:04:57Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D2q685yeOqr8SAQdAQNcFeSdUvcWIJHG0D6Grhbf6R6vfS+sbxBUBBq4pIGUw
            5/x6MbkP3Ef3HaZ8BU7Y1tA4qdwXaR1lcbV/5O0FREPJX3tDAQhOjXHBh4g3Zb5Z
            1GgBCQIQZjVzTQH3gOMuhcNUJw/Iu2aZmkH2uxHblZIjY3UjALI7+I+CXh87sGJ9
            oC1LRQVwEtaFlcmfEybnjjcVyBz7SrqzyeJg97Wl+sx/bpqM0e2ZPdRmXgxwicOc
            qlEk++qMOk7lRQ==
            =eXVK
            -----END PGP MESSAGE-----
          fp: D25B7C5D2B5FE33FAB3EBF4BCB6E270ECA40D3A0
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
