apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: n8n
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:9VljLAcTnkYWBKbwOwauwf50y7XJKfOt+zBATEu0BlIsgoUo69KTLRuUkPsXHg49DuwM+9MdDors4XQMB8e1wWn5RUyDwdzITWHN9Dr5xWwdjQg211akmMTL+LojbtWQNGW523B+EZYv0jhgEDvibUPAqhWtaJ5gPt5Vac2Ggno=,iv:BueD4m7GS5KJpY5Na2lwB3x8sOlVdKXqgheKz1syUtY=,tag:zLx6fY3NtMs5xT2FqhOxVw==,type:str]
sops:
    lastmodified: "2026-06-03T11:59:27Z"
    mac: ENC[AES256_GCM,data:N+j/o2dTZ8hKwBOMWCpFTVSum7nCadENpyreRNUEB/HW4HLE8ScadYo9Hx9+J7hVz5sXY/CFXMh9BoDnz5xiAmUA2JJ+YGpz5/i5fTNqr9oZoGFZDe610c2KYmOom6n50ZllEOO7Lun4xw6c2BZbJ7fMWdZO0sS7qjElTASER4M=,iv:BvgxGSWKqHydST5gVgo7b7xOCQtn82wNMAsyF9kMVZY=,tag:GhZEBy56tJgBmQTXZYbZrw==,type:str]
    pgp:
        - created_at: "2026-06-03T11:59:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwSeVs53q4TjARAApIm2mtje0xn8ymvyHG9MKQZ+/Wls2sRMfNsLAY1JaEuZ
            pyEqxwnX6uBWxIsNuJfM6dwlfTOizLqx8rNppI4TfLIo2rrrwVzHkAzlm1hf3JFs
            srjNjMg8pN6bS/oFZYydqNNrEWcUMrf6I/iQOmN7RCiK6AxMPiuJgk9j+51vqXse
            7OGCQT3h8fADAc0TGTN7bHaH0aNXym8PO/96xB9MvhJlnZH7Ku1ip8cSI+/Wj0+7
            v8lMFDtD9usH3EhLab0GrDTe6FhJvVJNX5M/ozFntb0Yp0JU3Xhg8xwK1dSiY2na
            2ZmEqi9U6iZK0NxR6wfIUtRpiKhxb1MHrDJTeHJjb3W/LoiCUhJFRwlJXwjUc1jA
            pOXFR3Rn8YvDcnG3DWL749TUFaPGTAeggEkxWRWSj3XrWXj0E3gl8vFDltkvZ+Qp
            F3ETJC3aw9F0ACTcve9Ecccu0q340RDYMRD1z5Bhb8vVhoqXfi+c8poWra1eT/5b
            D/Tlol7+mhgx2x8fvu7zLKXABpZoLCIL+GPaOAjfz3ePzNM1DnyNSu7GPq7S1CQu
            WE4FRs54cJPcIRPrI8I5neYLRVMaVEYLwgu4NrbzSjEXQxbqPJq2GULz4wqog7bZ
            m0hUmoTHZ/Gck8KChWHFb51IGlDigH4ebfS7KULT6+wVYfsWQ2eMVhItax0M0cfU
            aAEJAhDOkwSxaESJLQ8cT63L5bfcBdNWafT5uGEryYJWygTtWyQ1NA8ROtdKBjDX
            pHGCcjzdn/cCL1FWZY1+Ot1kmV6FQm/vQyZ7JPvswoVHbJAwKsckTPLfG+d55J+h
            vNW1SDbuGsed
            =CtIJ
            -----END PGP MESSAGE-----
          fp: EA65B90F135CF8C5E331DA40C87A0BEB390664D3
        - created_at: "2026-06-03T11:59:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D2q685yeOqr8SAQdAO2EjaSzYecfXfXUdPwmFQFTlsIUd+lg+8dspOXrSE3Ew
            wH0oTKs3kcH0oqjJQalY8wkdoFJdnB29a5bD28WKJ4XDTXVNw1cjFsxO0YLODgd8
            1GgBCQIQ3MgEoeIm3VKZQ1rT2lL0XOKUYTfTOu91Murn0xRqfvyQAM44rtL28ZmG
            N5gCG3b6je8VVxSJ/ZjwDR5Cd3VqyEEkSpIIMdygnKBgHEuB0m7TuPJLNmzfQeL6
            eStPUX5wmT6nSA==
            =eijX
            -----END PGP MESSAGE-----
          fp: D25B7C5D2B5FE33FAB3EBF4BCB6E270ECA40D3A0
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
