apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: n8n
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:YzKFjKAXIFe2JrJFwh7IX1IXjvlNlcSal4X2F8aZdL1CnYNHUn/icXeHIzcO8o4kGx7aZ1leRRfSJK8I7iZxrPfElvwE2TFk8ZT+VOWtPKlJjsL04LfwHczbrSD3p5PzhwqvGRPm+EM3dhRIZIqAmfQNuxgHG7seZrlOwEzvycc=,iv:zXj7ggH44IdKGL8wuLN8oBoP8oPNlGYk+Rh+742/Twc=,tag:PbJ2U6Hx/okiWuarc6WxvA==,type:str]
sops:
    lastmodified: "2026-03-10T11:08:25Z"
    mac: ENC[AES256_GCM,data:WogN88WeSjCQgJMaBz0QHht37iKwPEK1vVIPFcKMGwOwZbmQpEdEVQYpsM6eqY1IVN1TlPU/VUqWuSr6sR4ro7AF++XlhFfXJJqx6rwya+ARRpJ3FBUd1B0/7Bq06/m4nK9AXPetbPLadM1OFaftK8wagNn0HfARRU01UorJPTI=,iv:gbrNu6nj9wyOBVQkAPNcAvrO08plfGpKfrqRvmodfEY=,tag:wMlz18unjLyzV39PzuJ97Q==,type:str]
    pgp:
        - created_at: "2026-03-10T11:08:25Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwSeVs53q4TjAQ/+NKZc4d3CaL/5hPRa+nsQpXwpyStBgzScxauJ/2n4EsVs
            7/q2hEj322E1kpCt7LmP5MV9tePHIb0i9zzBcaIZ35o9qOTS1jxEZKqjN+nKs860
            mWuyHjt2/eRQnWJn8D9x2icsLaU3U2frK/0o8NtPnmEdIgOG79o1P2oTG5KUAl2A
            q8fDHrg6dBZrmsuQzY+xzL6I/9jR2k0cOmJNycWbpxtrwdQBxYzhXFkTl444Vgde
            lpIx5iiv5AEZEIfvDaahjgXJgDT430I5D4T0uMq8/LMgoNsbmYcbe4kCKKKjKknB
            jw0xaUYWBsVZ2BdKcM9NRzqdwb6zuTRgbGiWF5UtBy+A3NAjiS66kTzdyTvM2WyE
            bos+5JGrtNgpUhNC0ytXCVD4i5D6ZsMYtZbdPZ4QL9s/R0gNl3ZqE4J8ORrQI8Wi
            tenbyXZCrfnJaUhyaml/HCDF/0vFoAE2G2oS784e04WNcydjmpwaAvedPA3mcztI
            x73bmslCE7i8eQo/sa/aqazd2ZYo7FdJrBwcWjvJJV7onEudzk1CbiTdgAVMMp/V
            S4bETiT7FHxhgNKPN6TDIB+zWnH1uqBXWisV+z/l1R9cKeCwlRxMb3QMQw0EM0lv
            SNFCMvfkaArsLtrwrSA7FmQdg815RoIQDBIKKAseSoN7HKdialPFGgVDUwdrQe3U
            aAEJAhCwV7BhZbq0JJphajle8PACWwBGDGaPkxZB//+pfxXrsDSztxDNyt0ddI6A
            i6y1rNYZF6j8/fJAuPnql2wWpT7YA+U5SyH/CCLC06y6Cy6jAHaJlqhTYy/cKmdy
            R1U8+p6Mo0j4
            =hG6Q
            -----END PGP MESSAGE-----
          fp: EA65B90F135CF8C5E331DA40C87A0BEB390664D3
        - created_at: "2026-03-10T11:08:25Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D2q685yeOqr8SAQdAD1K3swewfhO7WVjLa1jdG0yZezvGNY4BARXBpuXBgFcw
            K52cAeGaXaJCTqqyg6fi9wjZgldjZpLMHrFeqjOTXwQZGySSx9IAfE+LGu9LJY1x
            1GgBCQIQwWoT+YxC7vJNpeg+IV78BDWctN7Xz9mHknacy+/lmXWzMwrgdnQX1Ney
            bNvf6Z/7F/X2yYAK58k+uFzBVWqSbEN/PplK1bcKKiH84A6XhjOWxHhyFtfo94IG
            PKk0PJlypofHlQ==
            =Pm+0
            -----END PGP MESSAGE-----
          fp: D25B7C5D2B5FE33FAB3EBF4BCB6E270ECA40D3A0
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
