---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n-release
  namespace: n8n
spec:
  interval: 5m
  chart:
    spec:
      chart: n8n
      version: 1.16.46
      sourceRef:
        kind: HelmRepository
        name: n8n-repository
        namespace: n8n
      interval: 1m
  valuesFrom:
    - kind: Secret
      name: n8n-secrets
  values:
    log:
      level: debug
    db:
      type: postgresdb
    redis:
      enabled: true
    # main
    main:
      editorBaseUrl: https://n8n.golebiowski.dev
      livenessProbe:
        httpGet:
          path: /healthz
          port: http
        initialDelaySeconds: 60
        failureThreshold: 5
        timeoutSeconds: 3
      readinessProbe:
        httpGet:
          path: /healthz/readiness
          port: http
        initialDelaySeconds: 60
        failureThreshold: 5
        timeoutSeconds: 3
      extraEnvVars:
        N8N_LISTEN_ADDRESS: 0.0.0.0
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
        limits:
          cpu: 1024m
          memory: 1024Mi
    # worker
    worker:
      extraEnvVars:
        N8N_LISTEN_ADDRESS: 0.0.0.0
      mode: queue
      count: 3
      waitMainNodeReady:
        enable: true
      resources:
        requests:
          cpu: 500m
          memory: 250Mi
        limits:
          cpu: 1000m
          memory: 500Mi
