apiVersion: v1
kind: Secret
metadata:
    name: postgres-secrets
    namespace: n8n
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:tBWlbXHO,iv:6nh7z8aocEe4yTFkoLWsjUMnuarpAWjm3dN7HfEKPtU=,tag:z5Tjc/Tawbu9JsJr26plmg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:al/9GA5d,iv:0dMWTOo9MUym2IBMhk79Zp8IP1GiGscQxZaSZLlJiS4=,tag:ByVzI34yQnOj+N6YwZnR0A==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:t8R/KEyfJawoORpA36bE2TwT5NwgNeSPKi15Ox7kLvI=,iv:fd9aEC3SC+KAbLMbs/38YLxJPcJ7wqgcTt1TxHiigMk=,tag:8ZTerjliI6/jKuczMbb5Fg==,type:str]
sops:
    lastmodified: "2026-06-05T11:04:53Z"
    mac: ENC[AES256_GCM,data:AfpBaQTn3QYzB1inx2HS0G+0H14MZutWUgMBY4QWtTLpiOZrhGTIvdxDIGDFyQzR8E29xe1pmOMfFdKVmlaZzhdSI/dCwyztXSAeZIH+5YNJAr0D2t+aLdsdfxwRWx7eiM0820AzddRP7lNyWQsPGb86MgMRVEU1W+RFiiaMnjM=,iv:NjEfilRLhG/GTSCNw8a0Id1lZ6aWHSS0s/ZtoEQohb4=,tag:RloVdiu8dhDbup4nx9Gl1A==,type:str]
    pgp:
        - created_at: "2026-06-05T11:04:53Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwSeVs53q4TjAQ//QztfUOUyic9AO6mT9X34HUOdj8levkG8ZeZ9gBdMLJge
            P75/0EkbwhF5DTSwL1ywW+P4uM1HRW7/p5adgRHQNeoJAijRgkYASKsg/nG1OtWP
            tWA3AAUVMJuN5y+vl00zrp2lLRxQazrQtAbCPHNJ0yf6/H16OvYZqlmvdTDzLevx
            DpZN3eclnUEP+lrwPUksPoQJKkke6dJZt8M2AhoNEvmHct+0ZkTI5fXdPEkx1NfM
            o4nj7zh2aOJXShRFQU+vtB+t/KB78/wTYVUgX6Jomq+zssI7OEOzN4ANv8fvnxQq
            UMqaduYCH1mYKUaTRCpGlwW74fyA/gngRSgWn1jRwquuhuKhxOyrnVPG74tRlw5K
            dzOgW+xjT6bzCxfnrFeXFFHUKj0flblksXYbPR1RBveCrC3ZEPTkRMlktqHc9Xyn
            2oKikvLCEJpk6PP1qsIeD5tYc+uKra1XJH2UqYUHl29n9E0yLzIMDZuL3FivgERr
            DXkgykFkta6XRouV3hHhZ6+ay+gCp3fatQmUXbw3pyuAbV75FPURb19dAr01RVmO
            Hnmi99x/7wLsPdiFlAjDRaBYnb9wBxRsB4FFKwqXjhZbzJJ38Eqc8OHRJaoozA7F
            pa1p/1yf0JC17YpNGeFAxkMf34QZQFXynwQpGH4IXTXqgFLn7bUU+EQL1LmtmxzU
            aAEJAhA1Jal9+UT6D95puWCr9HVwYp2xwbKPkX9wVLOpd4UCzwd4oPs3YNHeabwM
            uvGXlrylruQq86Lgk/kfwbsAcLLDf1g+MplsJSu05TtrSQL0Iu8my0XF+ZC1FwHX
            oA7+JTBU0qFQ
            =VxDt
            -----END PGP MESSAGE-----
          fp: EA65B90F135CF8C5E331DA40C87A0BEB390664D3
        - created_at: "2026-06-05T11:04:53Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D2q685yeOqr8SAQdAn/Dl+dWh/IxirUnasSTGj1n2lUcDY0zoIZ6X1MNrPRsw
            xANi38mZRL/O5Rkmbsani5N3QqVvqq7Op3frRogtbVeWBIqnUe6M+MMrF62AkO06
            1GgBCQIQL9v+I9auBbQuCmI7GGL3UX507/PHC/QSUCcfKRRKJGGxTaAg6oGYNf9s
            5Fla2cWEarSLx2yXBfGO035tFi1EZozC7HP3D9q6fNnrUlNhnT0uTyZeieysQ7wG
            UI9TH5xbKCMg0Q==
            =DAVr
            -----END PGP MESSAGE-----
          fp: D25B7C5D2B5FE33FAB3EBF4BCB6E270ECA40D3A0
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
