apiVersion: v1
kind: Secret
metadata:
    name: postgres-secrets
    namespace: n8n
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:vfFP,iv:nxIlUvefAQP1cjpLBc4RQrrk3VLEXQqElGM64IizkQc=,tag:/C3rCg/c6DWOgCZ7BIOH9A==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:JSTp,iv:w3d20FSxvtkv/Oz/3Q7RcZHyhqjNRtMx5E6B0KT/98o=,tag:XZocw2bl4MkUpguJ2j3wRQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:FX5i3kN7dR9T+S60vEe6KMN4QVdWX/QVA5sva2Ls2Q==,iv:MLwyxXqAzNOw3+51uRIPDp42njN+LtrwMR3Uc7mdAU0=,tag:6t2wzq0TEi003EqMAtRVzg==,type:str]
sops:
    lastmodified: "2026-03-10T11:08:15Z"
    mac: ENC[AES256_GCM,data:7YGwgbWcxmsasQcT9hT4rKhmfv7s8kRvruiicjAT3r54OaYirHxYPWWwdC9JqAtp3cLvFTJ8+e0/e17k91n8EO4JBUvPOeWhkM3kMekdfGCLtqEDvg4V/A6NuWwUFp5BVCTD4PULrs9kuFvmyciJQfvkEJxSb2feeijmW6UwTwc=,iv:rgRgAM94mhrdeY1eXWygH5FXmFAqQOsCJZG0eCMZNSI=,tag:TviK7h1XeZ+kOBwXh3U2MA==,type:str]
    pgp:
        - created_at: "2026-03-10T11:08:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwSeVs53q4TjARAAnpKEeWvoCLwjJg+N+2R33p5JqZjxbGMjg0r24WVL539x
            N+cddmPt1xfrq+QiOt6RfNLK6e9ApKTqF+e8Oui72JGcAcgoHAi7xxJY+YhKKSlr
            zeKyDpnmCIlqA0EOdeazp/SEByodQPl19Sx1esogTQ41/nnYbbQRFDBk9IQcDlOl
            DAEewyno/14a5nZRSwbj8uOf7Jyd0g1mrmK5YHJCl067IX8hJHil7ydLNrfpJTdA
            QLy1AVVByqd8BhQTHd0mP2qYhe4GaOhnBgzp2OTpKUmCuTcEJF2AaLJ+Yrhrmadd
            xK11mTQQNs/U7z3t7yGhJ9Wmz2LiDGipjkgmz75aAL/qCkiy2ZHxY8S9aBY7Ym40
            hX2lNbhtsO2f/w8yvq0XBKW1R7HyBEQIBR8fhQwA3Mq7A6MwrPBr3Qukz7yYC+0v
            elSmNYJ2AFN/cVkA8Bm+jKToT0k06Ll8NmKjQUYtT30Bm5Bh3u+u45lD+S2Wr+n2
            hvVXcjKHp7iuofdw8By26X0DNgK6PxWDaUeUf1cFnkGzivNTXjjKsf/YnqyycZgK
            Clp99nUAzi5QpyQaseIv5rA9LLoNkbq4UCgqb3ebcTPLCEyAoTGPl2P8qRnktIVe
            D4sMKh5ZwmlGOX7O8FY05k3c8XCOYtjinZlFePfdBzpsXbiBLEfWXk8W8kc9VFDU
            aAEJAhBa7RayGECt6TVhifXN2/t1As+auLapGkVoAme7NethhAkka3+la4330TBs
            s5mondEeo/ykO0MGjyZrGzPYNHFe+J1VRu0hdUorbBmdllrl+YZxIQSmHkg4bquX
            aGbIvGqoYfdO
            =qD0Z
            -----END PGP MESSAGE-----
          fp: EA65B90F135CF8C5E331DA40C87A0BEB390664D3
        - created_at: "2026-03-10T11:08:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D2q685yeOqr8SAQdAPMcinSN43YwbV2U7MltHdR9oxWRV6L/W5UqJgsLfgRsw
            rHEbjLwL0OsIHQvHoK4KGRZul7bG4svHegc4sBkrEtkcZPjDw24/9Q01yvRrpVgP
            1GgBCQIQslqPEUkn53VtHZNMm4ja3WRkGXmK7qeEQSc8MZLgawPDocCHY3ln5PQ9
            FVhoD+3ZU5zHbUvH6gL9BGZ9WgdN/mX+aHk2dG/FmmVmFrxfU7VN+uR+VxOf6M5D
            NNr2lPV1hC5fug==
            =HkOD
            -----END PGP MESSAGE-----
          fp: D25B7C5D2B5FE33FAB3EBF4BCB6E270ECA40D3A0
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
