---
apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  namespace: n8n
spec:
  type: ClusterIP
  clusterIP: None  # headless service: DNS resolves to pod IP directly, allowing ICMP ping required by n8n pod
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
