apiVersion: v1
kind: Secret
metadata:
    name: postgres-secrets
    namespace: n8n
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:tQ1wa7Lh,iv:feZyckE8Iu2JlKZIOgulCqrDYuPOobg8ReszlQiNXr0=,tag:pjlWZCFZ5ZxF6mG8HO7ppg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:ewO9jeoZ,iv:6sZLQzDexHyEXEkclD64ypoQdGhJsUBjPHl1JCwyiU4=,tag:9sRr2fxVP7QPLQkZrcEWfQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:PIcwYacXvvazl2B5F6o2XSA98Tp9HxBpWF/TNb1h7E0=,iv:3LfntvsEQlCIktreR9BellAGClIn9UuxLCJD/DJycBE=,tag:XLViW1tF5ZI04BywLjf3qA==,type:str]
sops:
    lastmodified: "2026-06-03T11:59:33Z"
    mac: ENC[AES256_GCM,data:Xi63nAoYXxhrKHF2NijP6hzGQ6SFxdSzxORQH7Wxlf1ckPrMUUGiI36Lobbn58GZPpls3/vMdHecj5U9cYjn1Fnx8pVWrpxhIQye/Cg+7Xs5FuRhg5gYBAy8EPfW2SWD0YxbcdLYG9JeGlRAHZVOxyxhmhujtN9os2W6+dWNBkk=,iv:8POnwYKPdhQ5QzoGQrkcZDvMtGeA3UUSh93bKuf0tdo=,tag:XO0tZhG9pXGZc1hBbR87iw==,type:str]
    pgp:
        - created_at: "2026-06-03T11:59:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwSeVs53q4TjAQ//c4x+YWLW/qpLurLVkm3LkvV5zRe6mh/1iiA3Mrq2zE2K
            9gF7IWeahxKRGyJ1Z4pFJVBGRcPCQv1z5ruKGrf3FUIaOENe1T0+VDlOMOPV5Jh6
            ZgyRf3HiShoH9xtNBuwrJGffQ6Uk9EsbW8q7/Z+xjBHrQJZhjdwn3wPmMRo/vCQA
            G54soY8jJyC6IitJcw0N8lvbj9uFa60tf2SnqQYjX8UqHjPwd7bBVw6t7np9+Ps9
            ZBFvttc7+Bn5td7SKyTrB3TxCa7ON8MYKeXA4yxHxUsir1VywLV/VIBh8Nc9R3ec
            iRquCQIhDHbxfDmEYZ1H+MhADxM6x0Xl/c6TCVfsQEqWMiB7jp7wk7OmcPJEJeys
            v6FBmxw3jBdkSv6CUaM7hZPXfLivWko9oAuIE3Ippdyo7Fk56xPm0P3fQCinobE6
            9dbNQAQvOmCLHgjXCdNY0IsdB6goF9pIlNWnkbauvLByobZeqdwudR1x/XFmCVtH
            /p5aQMqqyAC+CXjzIieHB9NBwG8DQG2TkBvLGZvRsXWgntzEToec0VI53f6o4zF7
            Fa5tUEaF8dV9gazguQvyGPmHoFZXXhuhjolryvR3TScsORsb7mrgaSkSFPeMsUYP
            ne/2jx5+sA5kGXeIkq5Qxb0cWLS18XBCK8uaHQWHNQpp/H5O5ekuHy1/hPiwDGrU
            ZgEJAhB86E/rDoLq0IWyLn4dQGWoukzJMnDCCloPk4pQOYzpkAKaaHrCak/PRaab
            4FBesU0jpSbx855igoLldwqEIcv9Czsk/Q7XLk/nBPiyzIKyJD+iEwstHqaFVezp
            J9LBcdTfvw==
            =OWtO
            -----END PGP MESSAGE-----
          fp: EA65B90F135CF8C5E331DA40C87A0BEB390664D3
        - created_at: "2026-06-03T11:59:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D2q685yeOqr8SAQdA+0HgkvTmFeGmrKw7cu2dNYIHKWTPuul1RoEwpnxCZQww
            KMzaHxVSNfsxI4sEfelgMbIQtrfZE+MW05iUHVWJYG0rKrgS69s0JCN2Fy581Swg
            1GYBCQIQOVjuX3oc3qqAVuYNrV25Lvu+V5OqXQudRVKmmCccWsDJ3X8kddX8MBZt
            Rh8G3CWh3WD2aBbOuXAd302juLYy89h+681qcrG1pYeIN5Up9grT6sHv1OEjMSIJ
            qHwmQpatV6E=
            =yIkY
            -----END PGP MESSAGE-----
          fp: D25B7C5D2B5FE33FAB3EBF4BCB6E270ECA40D3A0
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
