apiVersion: apps/v1
kind: Deployment
metadata:
  name: anton-docs
  labels:
    app: anton-docs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: anton-docs
  template:
    metadata:
      labels:
        app: anton-docs
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
      containers:
        - name: anton-docs
          image: harbor.golebiowski.dev/services/anton-docs:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
      imagePullSecrets:
        - name: harbor-registry-key
