apiVersion: v1
kind: Secret
metadata:
    name: ddns-updater-config
    namespace: ddns
type: Opaque
stringData:
    CONFIG: ENC[AES256_GCM,data:d1iN+2BPQfn7NnQ4YwZcNRXqC0PTCdcp7T+iv9b/8or9d2H3VZ46KGCFW7CJ0Cy5Q1Pp2aUilok2cqsvclbBmM8reuFXBpTfhVOcrVk7QLJldK+NbqE2npj5Cf4Cwff95utl1pKmfwWKNXfLZMbNvTYu8xHlF8CX490a0+63dyKTbtSq1ztjMmBeefXr5i/K1DyKpbVQXzw5NxttzAYAQ6B30W/0AixkIpxLJBF98VMtJfoodhGrWLfWfsDIEXZBAPyWBPIqzpPi+ZDZmOmdtkvNhXan3x77+9WxV7iqXfy6/WNtOZw5nhdeez90DS3Z7/xpt4fCcEzi0LD0s3zfCdO7O2AG89Hf0yM05sCufj1wZZTmqsUJMuNENPurcMuszFNwp9iGH2y+SCOQcaB5O3gTg9TvQmJ2y4ThxHymJ8DFUEje445B+djohiY/10WYsQHW+lFcfJG1v2ZkT+A=,iv:GIyIyUITTZoMRbzd7FDHKaN0ctmUvmDdyeUu8WuRjPg=,tag:I1wJ4MGHw456PUU1xZPPqQ==,type:str]
sops:
    lastmodified: "2026-02-02T14:48:02Z"
    mac: ENC[AES256_GCM,data:tlepNpI9RAR5QosvSLVznNyzYlVhUMCraukje2gh/L61nioBrulz2MkteUj+SPLFDOdMQJmFtP1+WlkOux5HWYA6xXWkYdYPDr5LiF2s/2hv8mqHoGF3oQ/OoGlFtHqsPr4p06ZWZOQVkPzzTYAUIZNwDQKPc9yr31zkuGdfWAs=,iv:Q6xWAlOSDq/BM1Dn6FH3i1WlFuvFHNQWXeqPjMyULhs=,tag:uBCD4s3Vkwp4H/g5esSRUA==,type:str]
    pgp:
        - created_at: "2026-02-02T14:48:02Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwSeVs53q4TjAQ//SCAd+4117oWgaKidxGEsdxwgL5jS6ftXTK96Z6+6uXQt
            BRdLPDdkuAhaAgOUytPcNiRJGJzf9itsRIwE/OpzbHTCmCjf5XwVYsLJbc95LNiO
            eXryOPXJH1OCovJ1+VSz6TnDDvFOQBikIgaR7YM1deTcf2/gAZ7S2cTwcKQqioOr
            IzWy8KpVpiFikm5CZg8+xRLyIqnWVtRmpzYFXP9wBXd2QRAoEjM0EeF7lYKE4PdX
            9dP6wCGOPR+DdyPHGLrDum27A3d/OZh60AmJku0hK4LX7/2/ZM64aqi/sSmMGfFb
            sHIypbUQE6e+EKn1jQeGEtHrBAs4bnWWBvkOFeaLNhSPxADXBNM40EPkaNpmyFqQ
            FgKi9rfITr0bL5Bb4ODVgzpa+8bS1bQnvYGysKPz3CnicrZH2D+L8Zzji6xBIEQ2
            L5xybQgDlNqWsIIG6APNJnEKmCveqAwpahdSEUp2jEHQcKU7VJdKaeEQVzRHxOK1
            eSUzOQONrkRTOxAcurousl134eDoBFpp0PsMOQ9GarMX6hlgcaFeogBzFhHif6AR
            nfswRU8lrbaMaZ+v/4MiB1KZ4PUPlkKUHjcMStMGuGufsTUpmAVfWO+GgzV5Xh0E
            BvlBiQcRp7vgKp5Y/fHghn5l7pu/t5fz5VLj9TCbU47w0vUeMubzAugVqrfSuOzU
            aAEJAhDQ2/zS81sXzv37Z3CCbKAkSJQtu5ORA/MQI3qwmmNSJJik9DRuwlC5SPcE
            jXNrundRiHtkolsaXdqzl5KmfctE5IJyA6KafJafkzONXlYFmeunTe78wIAPedbs
            QNWYkCwsnxAe
            =yf9c
            -----END PGP MESSAGE-----
          fp: EA65B90F135CF8C5E331DA40C87A0BEB390664D3
        - created_at: "2026-02-02T14:48:02Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D2q685yeOqr8SAQdAnUH6JIQFtuQvGxMZ4ccZmqDODxlK7Sw0eHeKodRdBmAw
            Z1T6Jd0lyllcP2stVDObD79GASABl2o0FF5h7e/JtCaNO8scXfD9f36DH6TQnIeZ
            1GgBCQIQz0lLOf/HKPRlVjjSHOAhWaQQ+YGm8OWaSgzf/DGbujxTvdLLGNP7/f9V
            D2ZuiurNmfozwGMOZLj+WVxaS+ODerAVOwuRORqaW2DJgihruoBVVdj36BrgU1s4
            FgZuA5Mkk7r65w==
            =XdOr
            -----END PGP MESSAGE-----
          fp: D25B7C5D2B5FE33FAB3EBF4BCB6E270ECA40D3A0
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
