apiVersion: v1
kind: Secret
metadata:
    name: ddns-updater-config
    namespace: ddns
type: Opaque
stringData:
    CONFIG: ENC[AES256_GCM,data:PfVq2EjpVIMd3dNKRYdcCNe5YTDDAPjr6/3OD4DcGRGe6O+CL+0wmrMcSOaXya3X9gGIrU1j1fX/7/qzbwS49j9WwtkIcHN9ooZNaFX5Gq8TTb3krdsqTP6LuOwX5o1ii6Vt6jRg5NBFXsDOAIIGv3er6Xqz9s7umPKoP2pNtqIsoHECAGD3YeFdKs9v2ufl1caeP6LvA7JlXvlLTtr4uw6tLbvTMDpo1K1BCuQ3wEXSeaweHlXRxQkRwoL1W8KO1WPFEmbXeFyxK17Hhh41IxejG4BaPj20zaVOL8eZxh77sW2uAAl0Vvk2MXJRogr73MMh6CmiIrWYpv8qhBedokuTKczcgEH+KmtcBw8cBYp+1QkiQ/3cOwqq9hxxdxYaWpAPYpBzQ28FsexVNUN6SvQlkEfzV0JB4d0UjpZ8qbfyeIjNvCyeA88ntDSzUM0we0yydGbodhSR24xl8ECGTIusXibbMUjGPi1HBQmTMmdMDkZIwi6TIpmxKbHQT5UxNpDTRLYHur1/ReyjmjsN2qHxWNyUxZOQi/QC/v5KCz7cReeqmetUHo9QWHZxyZlPnK10CJXh5G6ikhK/DYe00BYPRRByXJw0Dm9ajle01b6CuzToaGsFS3n0DbYOcsqHYoN1E0hWaqUG7jMj5ww0q9vt23nxiiF80rHQi4c9J+yL5YB5Ti0Iq/vUvFDks3KkQ4XwRaJlJBTUbq9NPhP5bLZ7kZlG6M54zsrAvbmlP/7yU4RYGEG9xjt65kngIoIInJk3SQPodatiQBYyL6tiqRkapvVnDbcnmSvnFtktytOPnejVOMvnqGPkGWDdcvjl3iM9mwHjE4sBYyl6qHsrkkExhb8U/THDwzJV4HXrbqxKAQ0Wx4J7BxD7j/9ZMSILXCcup4fyAz0Srd7uO1MqTlmF78W3rk9AIXwx4+2aK9PMmesYVqW29bLRcszaWE/YgqHxtIbna4p5140qkuafezDExvOHI2IpEbuaQTOHmQ0YiE0bJmjqXND2keEdmfQilgvoeBio7CKWpeYLSv3A4Ly87fdKUGRbq4AjQQ+j5OV0uFo+cE4eReqXTmzjCdAFjd75hZXr0kGBW0kuaNAiajdyWtnNb+zlHq91lM6AU6Q2Jy/dGnH+dWOmRD8KjV5Oq3pzAi//SsR58mmUbUgc02bcjsBXd6uHsxyXaZSIoc4HhTjuAlP4SrzEtkHybsVpDNn5Plb0vCjzUA99D3OJkDiMTGwqGjb4PVeISJVrPBE5CFgejRdZJKE6muE0t86jBGyzRIzx2cUCcteQjdws1tboHnKUgjP453gXnuGZL7Z0buDi0Ed9uxUw11GXiMfeXhkxOtUJFup8gO1R4yNu40pFHjwjmqgxfj378QI5WpgDYq/v6CkkBy3ZLP+taZ00jmVNuOAQ+C3fNT1oJ1dspcquPaTLXxFeBf65CS20HAtFJAEAVDSYT24kjjsCQZJ8SiRzcfboniY2TirlUoF4dE1HEUFeiH3xs7v6K3d1pgj8Vif4WoNrbRAyHlgx9hJxYdZ9lvwudl0aZQdxyG1rWVpFMeqRkL4KfTWDK9Kv5a1mSj1LPkbBNmw+v0g2eOw4LiizR1T3GaGxebUMBZaEjait5x/MrO71JkOPx1Qdwf9OQVQlOwakINKHo1plVy2Amh42ZHL6PZ8HoEof1xQpBZRFI+mZ8ZS6L2ouYMet9GhLQDkd4nejxJyscBYs7W0J9YUSZaW2wYZub3+9kIPM0btgyMC50hGFNEtPDDhYpxWbiqjqteZg1hhpLE3dh3PQCy+Q/O9mQMwUHsTIVcvJC0aj9Laj9fYsUOo1WGeMWQ4IwX95VtTlTXj7JnUYysja7551QcKpUIFfSngz2hg6BIkgu4L3f8ksJrnlMn1cVod0OsD9k8v638Teixj7bie9e/5sOIgoRHlIJCXrC86306twqQ7zHXFiF0J/52qXu6fTdaZvmDNH9NllyBg4IbZX4geOuz1e6P44eWE/2hH93TaCx3We2QbYVgCcvU2Gkxd37AOtnoP+njLLQm3hzY77s8rElOUFxWo5IizhDVJ/lH++Mw01e14KtR0QC197zrIdWZCha9zl1pnOGFsGbBrLUEHjSgDtTRO5zOycZc+RbQNhdwtHmrtcel+OmxiW8I8gsvBIHRRmOugCKVSgHmVwi1VUIVd7yHx2Wsl2eNJu4XXrRyoR9mYs/d9tyn5ejAO33eTBj0PimKD4lDaihN7fMsLq/ZUCVcWxbyBsA8/kh55gKqUUX2SdxuAFCc7w3T3X/ZDyV9GzmWH4rwUSJvSz4ZWwLke9twcp87DFRm5KLP0L9Iru/ePvsro0z3kh4SWnxckU8gfUnLxzaVJEOn5MkjydhOJVVi7q+c2x59NRxMRgTifS1tWMSvBP2PzPqDFx0/or6mC/fIP0lB8mYUi/oT83bt9H/3b7hRIR6ypu3i6iwI9DJEcJWrykaXYodE/8YcEuCqp0DIS6gtAIQe1z8TIsH9EDr4GwPBbt8iIS/OpV4sXAJRfzq23v/KLPGHWbs2PoEV/Fk1scUlJzCg4JbQpl75M78Qh5tD6ad0azIKFR9kk4gZ8iNzSqN8PUTQ8SZanj5duZjx6p2kl1STUckdKrCjNDapUmcuv5pIJxw0pb9fcad7q3vu8vFdRimxJpYX3qNHi/LuZE+0lIvPtJUbeRnE5bl/uQndOAIqPQHzESxviXnbaeG0MaJ67ERzJqUZOedaTNax12BRoPKu8Cb+TiQEoqgUJClZg4jy4lGNMOdcShafCI2X1FU/JFIxaFAMxkJ2Sb4Oky9K6xomBgddvqbgJKrK+M+qqQOkDv+oCsz4R5aKj9WyG0Q4PwbRaQCQ03elWJ964WJO2XcHM+KhY6PAIIvKKN6Ai8vStmf23dg/RfTwXqKEa8KVDzcmBpzmVlFHwsDazw245ptbyod5o2BneYyWCnNijj3Ga1suOeZmkcp2RL1GUyJmkyyStM4aJnvrMwGyyNM0ZXqw3cFaup,iv:HsK7lgxju10RlDnkQhuUVPIdJORbWNiMEQY3HKb0T9M=,tag:3+0hLPoEUAr7VYuEJ3Nr0w==,type:str]
sops:
    lastmodified: "2026-05-12T18:03:40Z"
    mac: ENC[AES256_GCM,data:baOljWzOFTDQSKwPRp8WM5Z9/N97wwkjMqCcoPhqEq0Xpmq3Kz9Z94llOeKDnkYI1WEy08H6rXzsrm9qyro9bRB/M+GoGsKwVvzivll8aHSxbr8XZSYrB16/Xf+bOfo5GPVet/5X6cz6ZM0pGM8nk7zv7nee/slcV8gViNNb92Q=,iv:2R6gdZoIqBsBHFkDMZpxOS8Si6wLJoo7a1HRWvB5VTQ=,tag:bUrtbkv+9j25xVd0Kgpd0A==,type:str]
    pgp:
        - created_at: "2026-05-12T18:03:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwSeVs53q4TjARAAro5O0lgYbCPv/5lB55n6f+nbHmxiY8dpmnQJKgAL3w3n
            74zmNO5kUONNe0dlF5ej6DzejQOIVa3cGVl+GhvVD7kKi++PIUo4BRyr9w6OKEUk
            Smr4z1s5+zRXl5BFVwcUZy8ILnVeAN3b8NXsNUjUQ669mfgkO8PIkbYWHR0C4o8J
            TbtBGB2A3W9ObeyzFFLHsA15VDGc0WuvWGJ5zCeNIfptFb9WLhdh28XMFhpwrX8m
            hTzJ7vlIres060qQXc8Ekgd4Dp2QGSdxzYl7u7lNl48fKGUyozRz66wOAkPUhBvj
            3ZJt2Eq0qin/6CdUhUuqzbPykT3/jWwgfMADw1lrXeD5CYXO/mPawDzMAF8jWhAZ
            wApsmHwDzR66myUIVC/hZGvg39XjJ+Q7xJ/bLvgsKSMmH8Tj0d4sgw2892vqu9rv
            asdL6bWj7O3rtm1XU0MKSonuDCoGw3Ft65novsowwdQtidmEqluzYx7qSGt7Z924
            jtC61U0Owc7YP2sJYKf0TAT5ag9Wjw8loIHZnh0xfEOkUa3CblHWStJae5LmxqUN
            r1IeCCh0C7MEITKTFvj6+F+pGcV7WXCPdAZLP4BO9ceBgGLL5n106UTnWSyBf0Lp
            miX4Mj4YdHKw5U43InJjIYEY7C9NTdKN35YpV5pv9UolfW310i+Sap8uJ1NOYuDU
            ZgEJAhA5MM+MLpMBItjYrB3vu0hid50QDhr30tJejMQkpK2+7y2FN34LJYL6rmKa
            +aNps/R1Z5KAwpjRQDLg8DL2PUWFGcfJU3GXkIkUFfCe1f59GrlBBYgOHw9ts6IZ
            cYCFtr7b0A==
            =Ma4y
            -----END PGP MESSAGE-----
          fp: EA65B90F135CF8C5E331DA40C87A0BEB390664D3
        - created_at: "2026-05-12T18:03:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D2q685yeOqr8SAQdAdpQGVsfqg03eO8MR20UfGEXyf2p46SEB5sSpqEaToHkw
            lHhXnKMHZ9/1dM0VeWbFO/3VsrCn5JQ6ArkkhcMHM3H8ZCvYbdEqi3xMabVerW70
            1GYBCQIQ3vNdo8xrXHLRwozgbL+5AYljwDSgdraOFCRqNDWFmSoakfzhqGA+B4Nd
            emzr+UClbWJ8KqwzFr7GtGIo+mWs+rdIJ7Lg3vD/KOq6H9Fa8qQmBWrlKWsvCyFV
            AG+qHHwkMnI=
            =10P+
            -----END PGP MESSAGE-----
          fp: D25B7C5D2B5FE33FAB3EBF4BCB6E270ECA40D3A0
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
