apiVersion: v1
kind: Secret
metadata:
    name: gitea-secrets
    namespace: gitea
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:ONcAVCxtXo4GpR7IQ3zwUAmA6MoZUPTbBj740IR1UWHAlM88M/N9cZG2/AACj74J3xUlGTcEc3mRfMRjdD3ZlgS8N5Dk/de7zzLcDrzJEHQWN05+rndt9s3DsZoJGWuk75D8k/drtOTwDlMuk4dotAk1LLNn9iQ/u6DC69Vp9vqv6J5vXZBK9q3XynvyZznD37bDr+hZEwLkJaq2Ft/P/Ss1Rl7hC1nO1Ka+IPNdWimGLi1IYp9t5YWajkgdYFgp9r9K79oEvOMgqNqfzZldbJAIChLJgLfV1EaDJKj8dlF0ujo2ZH0ZTe0zlzb0nSW3+hwlnHCSxwj/+gQ=,iv:Fbkk1D47boXfWO00Ebo/eD6hIkOyZzhyWdkmaR77A7U=,tag:JeYu4GbQASh5YOMfYJ0dXg==,type:str]
sops:
    lastmodified: "2026-06-05T13:01:03Z"
    mac: ENC[AES256_GCM,data:u9qzZ+0JYV0c5RlSNgxN0Alz68MRBA+/SmQ9eJDDjb/t8HqAchmO7warno++BsCQ6EVrFQ1wi9IT7Iq1/ejY4LSLzMsjX1FM0sAEjK6vlwmAK1yUbKQ71kzq/kDd6Nmb8dlb9LkzwxC9crLNzvDDwbNxUruW83WlNQahLLQkc3w=,iv:wIZIriwcEHHrVwRupQRXhCBFZb+tQpvyvx+IB3EF/EU=,tag:qTx2G+8rqDGW9kV2+Kkv2g==,type:str]
    pgp:
        - created_at: "2026-06-05T13:01:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwSeVs53q4TjAQ/+MMNCDMEXscrM7qym5AVhCxk1EkXZvu8xYb7CK0bvFwk+
            ToB081R3POXHtuCYlYnyPzeU/1Nw3UwwC+lKpUnkas2wt/VuKIGVM5tAu6ddUIID
            sM4EKuRPGKm+bz6AKoJ1deHmit3TfN0wQk4JM3KVig0X+i1uX9lLBM+5nM2hxctN
            pklKIUKgF0rF8NTst7cpweHdQ45CVGZjw2p99iy+x/tb6oUayWiTWfI4Q/03b/4Q
            n9fYTMMIb0gnK8KNlxtnFyF/AgcFwKTMqwr7tizemKBZj1bln2S+BP/s0lUTBNZi
            1/639gLaYUcEr6gjn7SbGzf5qmcvAbc8/VbHvJ7h19T0nvcCXqmOny3lG7Rvw9iB
            yBkAY1PxdTU9A7MiCZaea+U9LUdu3qGX0ZgvmumGXKxKUkxkpsv7IRYbIUGZmZTH
            QxG1dod4eSyW6dX0UPbCXBuNjO+31PIBh2yEloxA74ZQl8oWeo85m+MPZYU/1T+T
            kB+4eHzGbJj1gm8CSzH1dPXJxXtZPu7AjFq6sUH5jHvSTLi8Uho40KoElwAbGAHP
            Ok3Xfnsgdy67Qd/1ROHa3Rz+hrNKILzhdrcWu4yDqkzVeMYvQ77TARg5URa+Cl3r
            UDPhY5gsg8awV078uGuWPEGmkE+MBb+309Y/W41zU0GW32yQw0vxX5Pkkjm9wBPU
            aAEJAhBbKc7YVQf4GNn/xqG0d3j6ElL/xnqghxLJDrCuLukdkgqwEonT8+4PFH/y
            SQDXX+Z9k0gkj5OO9JkaOtRgItFc2jGAOJbflXRQ/r+QprggN/3XQb355/FCrRMY
            nRvfXtdFfRFV
            =N7o0
            -----END PGP MESSAGE-----
          fp: EA65B90F135CF8C5E331DA40C87A0BEB390664D3
        - created_at: "2026-06-05T13:01:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D2q685yeOqr8SAQdABGPYf/mVqoZR+aM/NWVUpSoOqVJqflAiLhZqQ7y6uV8w
            G/sn1skGb2udVrTyFHwYDzZwLmtClujxw6yWHy6wdmgClj2qywxoJ/9i8BzUjKK9
            1GgBCQIQ7v1zd2ockr/dgK62r1th5HIe1s3SzFZIowHjJRwHxQtq98uozFjddtrl
            zgBMyccnfn5d8WdOeOD1SnpdgTi2tZ4wdjhETXaNW5DIPoF1MrSpUVXCBt5jLmMB
            elSZrnpR8OVxHQ==
            =BCym
            -----END PGP MESSAGE-----
          fp: D25B7C5D2B5FE33FAB3EBF4BCB6E270ECA40D3A0
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
