apiVersion: v1
kind: Secret
metadata:
    name: postgres-secrets
    namespace: gitea
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:3QTwyi214Bg=,iv:+UGYQTUVBvBH2m49GtTy5PPazkQR8NDiV1NyoM7j/30=,tag:weXJsvmAraZri6HWgLMPtA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:FesfJwaKu+g=,iv:3px1g5Rd9z+ActmWCB/0KW0JDCtjMTue5kHcinrEOsc=,tag:QtaScuvm9e4DNoeWwqnqkA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:OuuB3Ypt37RVanPixK8kwp1AYCmdwFwM5ks+fvH23Q==,iv:0uVz3rvpS/dLYD5VcilYDyz74nIXjRfttgKhFZ2XWGM=,tag:NEyrm+jE81uYI4hCklMsKw==,type:str]
sops:
    lastmodified: "2026-06-05T13:00:58Z"
    mac: ENC[AES256_GCM,data:7b7B+vjy+HHSaqLDfN0VXKC9Ejvs+v1vlKipr5Ybx6jLSt5ENaGXDFd8Jf6BivGimr/Sx53hgcN/58wQBSty/UyKNvI+F80eiHIp7hvC5zo5YPhakFK5LZRHw5ZWCrIPC9/h0crJpB/x5CZLcyClGLCJzjpq4+1mT9j8fXAex/g=,iv:V4+pZvb0HPFNP0TrAl/dd0Hb2ciqam5LA1OdQmdniV4=,tag:sfrfKp5UC20KSBxBAZXYWA==,type:str]
    pgp:
        - created_at: "2026-06-05T13:00:58Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwSeVs53q4TjAQ//YOcOwF6+VaN9NB4mKGJrLYr8OpqLd3BwCSaKekwFHYGa
            IxPwMximfQDSZObWH9ozInxI3KEVgwSa68rp/k8KBm0mkOAUBnycx8P0PDmiNQN1
            P+ALy4lxOT7ipYgE6r6QQTc0IY4+vfjrNSotG5ofSeIMSwfj0QMMFz21A9YSg+iA
            elGmY6wFu/L5UyuORn03AmG1uY1UwhlTDfh8JyZYZxcZphIlqFXSiEvN/+MrSVBw
            RPFFWNFARqfD9u7m8A5kWIbEN3XZElXzH9St0JdkYLd0c07308GPuJiUld5CpTe3
            QmhrLld1DSJMroSnNraAAAPc6Hna2f0uP+LrXF0NtbzuTeSyel2vPWoAtikWuVAi
            V21dZnU6aZfXWBMS6693Ou7RNlXifb3AikwAhLXVoXC6kqp6i+c+HRyyrCt0f/un
            tuyTZTpQfuhHwBWm6tvZKhA2FWJ3yz4dy3sX40axQAOxIkC1nsT5h5kChNYthWaz
            DuWEEs61AZtbnDXQdv7HEvQ7jcA5MFWJK1DcvaBOWDCUniFU7ro2lqWnqKN2OlpC
            3kHHOSLHbm0ak1Cn/Wv9ZmAGMefh+Fr1n6jQpjnJFRBPkgYZQ1AuyHy3b2KIijQX
            8pTe9XgNNNEEDLvLLK5axUxM99qDxECLOpRUzkD/0+geZKMgmjJxFjiSzK0e36nU
            aAEJAhAgf1/eIyBEgbKSD0cnl/Mu/Y5OZFyoVwjZhOksZBrnG83v/+JtCJahGzJo
            bY7IJ4h3cn0Bj0giV2XyzvlcniojL0g3DejCaY0ugHI4FhRQ4GRTnBqKa7zHvLTn
            ZPXbdc4NMLoB
            =AEE8
            -----END PGP MESSAGE-----
          fp: EA65B90F135CF8C5E331DA40C87A0BEB390664D3
        - created_at: "2026-06-05T13:00:58Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D2q685yeOqr8SAQdAWl5d0sTU8KBNPApJro0qDpK2UK85EvAjGPHNqrkLoGIw
            A3EPk/Z8KioFPpotsvPdGSoFSBvZXVFQJm/O/nKwpLe0dizx8cQ8iGWmYeUv4LFW
            1GgBCQIQkjcYvY1kr7yu9r99a/SqJaitQRt3bXUD1jTeO3W+GgqX9IfCJ+X5pSWw
            dhxC8vzCmM/+Rtl7UoTw4CS5Qrq+o1y2uwDFzXDuGW2yHMZihRtFqKrl3oJ7+Sq0
            eyQy5vDAawaNdQ==
            =Wyvl
            -----END PGP MESSAGE-----
          fp: D25B7C5D2B5FE33FAB3EBF4BCB6E270ECA40D3A0
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
