apiVersion: v1
kind: Secret
metadata:
    name: medicine-assistant-secret
type: Opaque
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:tPAf4WCadzp/GJuFEYvCy33Zvm9X2uJ//N2zxWynK4DIwPNoI29YkfGoEpbyKsPWTy8p6yu0HkB5WFwx04znlg==,iv:Mj7WEXANAPmolTLyXM67SnXpwTxO1koB/wHYYO4VcHw=,tag:wskkwsyrT8EJyJDZVzJkrg==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:S+1EGHoaotv4So5rYvTPTYi1eHbi75i7gVLjON5ajNFmGZzuL+pw4eQp2zCbY6HeIWjDCD9VWB7rqL189ojrSQM2EB+UL3Ho,iv:m1wkZwKib5kjZBtCTjw0DyvJiFTZK9oYSnRd9nVSEXA=,tag:o+5sRWwlDIOtQjvXvVqqNA==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:czZigkxqqHog4t+nVlzZEOh9yVbk4wmJFz6dWrQ4ejNDc0M=,iv:YSnHIQ5Z+9su+RUwVjwqJMGriiSF60SgbEtkZaoRJ2A=,tag:xLiN/hANHJ/o8PCsRG5hDA==,type:str]
    GOOGLE_REDIRECT_URI: ENC[AES256_GCM,data:/ir4BgAGRxxMadq17EFFYXsZzSZmZAac9QXtEOr8CXVoRcHMlWZiIEWf7i+XqiuhQx9tDGV0Hg==,iv:Jn2qlCS5qX9oQUJR8GTYNLE150k58zv4+rOs0LR2CYQ=,tag:Zs6/Xa0EQxV9R2AxjEd/bg==,type:str]
sops:
    lastmodified: "2026-05-01T21:15:22Z"
    mac: ENC[AES256_GCM,data:hrPSJxUIEzBPQH3hS94X4pWwYL3fHIKhegRCLwbyOE4sAd3AW5ptKgqbX+RUBUZsgsER0i20Apps+bOoJANUj+0AsOJUc7Cq+BynnoJblXRDdqflljGZC3+6hETXFfuQNWC+AXeugtRP7ZBj2z38uL8lnpQl7eXYUFiR8VJNRoU=,iv:j5jFNVkS6cjxaTx2inXKJjuoqyJw0THfn7M3mgZntlA=,tag:uhww5fJ056xLqZZwAa/88w==,type:str]
    pgp:
        - created_at: "2026-05-01T21:15:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwSeVs53q4TjAQ//XjsjZo24/jjz22WvUcLWbbEMAeYTWFjX/GRpycQF310G
            imqUNOogeEh9cJgl+UOuifLj5x8kXjPJe7lru/WcGH67zCb6aOtgCoeqONubKy4V
            a3qScOX2wJem1ZFq+ZRABakG5AbFjQVX7GWJyB1s8UoH0hZGNZoUAYJj3LFD46Fv
            6iDNMF6KiFNYMCOKcJyWVJ5m/StJK6F/bMIWWZz4Re+mR1Oo8R9fh7a1qvCq1nf0
            eDPMNA+J5IfNQZaVyoi4QgeOB8hi0nRZzV3Z/h0NEN2c724Cf3bJBO8eunmXUpA3
            Ehsq8kNwUM8D59eZX8Zdv4fu7w5l33IYhJ6TM6r5sK+CKzzEKtyWC5EkOyZa7Bpc
            B+n8Vlqt7hkuzdccscdqg69GLgcftZ/sEekUYFeiU59CbBcy+DhcT5QOR0Id0Xc2
            8FdbjEwv5cNt8anmXYW9jnMyWEpY+zUILVhNcUZI3fDruEkuP/8FzGJ6R13YVd95
            yk7/BqKpNKfshuFZmpmhDEn+HtrxllA1rzdKoGS8pRBD1lrjpqJ0ggR51bF7Ocw5
            ZpOMpcVK0VBibxUp/ypx+W/JeYcS2hmUXsOWS2U3dXNJOZXpyh893ZC1oswcYCa8
            FZspfD2N7MvGYoHHraoIc4zLWUVPyojl/5vnL+kfWHRuTCJ49Uc6Z6+8bAMcnhXU
            aAEJAhAfuQROGJiTGvTxgcrE9W/CfPs1cJ/6rHRPejIuQIQDYwd+YmaU9tZaAxFc
            GfRtrKFQVfbusAV7izpjFzCvTX2xg6dj8eHO+9RJSL+QV/arwvOj5b0yNMyNnjhw
            f31Bjlc9Us3U
            =cxxa
            -----END PGP MESSAGE-----
          fp: EA65B90F135CF8C5E331DA40C87A0BEB390664D3
        - created_at: "2026-05-01T21:15:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D2q685yeOqr8SAQdA5VI+auJ1Fb1LzHtxpHqhJqoTDf7F9g3K+ybgPBkufGcw
            4Nib/w1LprKignfEsKr9wmIfnFIADt3b/+N7M1zsq8lN2Ey76PdoffOlgzM3256a
            1GgBCQIQnyNHubFWlFmZtK9zUvR7f4+vr5WBZnGF1jdg2r0aqqIP7Jk+SV1VEtjS
            sH4koJtQtrzFGHeCqr6pyZwW4CxAe6VwHRsjxdXUellnU19Xr2pjavbf0X8fXdy3
            gz0VyhLF0XyuCQ==
            =n7XE
            -----END PGP MESSAGE-----
          fp: D25B7C5D2B5FE33FAB3EBF4BCB6E270ECA40D3A0
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
