machine:
    type: controlplane
    install:
        diskSelector:
            model: SAM*
        wipe: true
cluster:
  allowSchedulingOnControlPlanes: true
---
apiVersion: v1alpha1
kind: HostnameConfig
auto: off
hostname: overlord0