# local-path-provisioner.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: local-path-storage
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: local-path-provisioner
  namespace: local-path-storage
spec:
  interval: 5m0s
  url: https://charts.containeroo.ch # https://artifacthub.io/packages/helm/containeroo/local-path-provisioner?modal=install
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner
  namespace: local-path-storage
spec:
  interval: 5m
  chart:
    spec:
      chart: local-path-provisioner
      version: ">=0.0.32 <0.0.45"
      sourceRef:
        kind: HelmRepository
        name: local-path-provisioner
        namespace: local-path-storage
      interval: 1m
  values:
    storageClass.defaultClass: true
    nodePathMap: [{"node": "DEFAULT_PATH_FOR_NON_LISTED_NODES", "paths": ["/var/local-path-provisioner"]}]
