---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-java-aether-pvc
  annotations:
    volumeType: local
    volume.kubernetes.io/selected-node: worker1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 30Gi
