apiVersion: v1
kind: Secret
metadata:
    name: mc-java-aether-secrets
    labels:
        role: service-secrets
        app: mc-java-aether
type: Opaque
stringData:
    WHITELIST: ENC[AES256_GCM,data:ymX9Eh8q1QLZ7UH4FbUtpIUBF76a/D5LgQ==,iv:Py76B1f2TUaQ8ERnDNUt7nIy4wEAEGNPZ/AW4FRua2c=,tag:t+HFscgwcrqR113sCGK3tg==,type:str]
sops:
    lastmodified: "2026-02-03T14:15:37Z"
    mac: ENC[AES256_GCM,data:lDGP/E542XE1mApLX5ecLLuhoU4kdT11kTJVb+h8xxzq4LQMLz8W4XDvfhy/Mjs4N9dYd7AaCqfopU5CMeYEpWEuk/rizGmtpF2WmKuVrMeehj/ohSiim9RXvGDldI7fM7l3wAtrIPq6NWjh8ogJdd/bKv5PQLqcvOiH7kO1czQ=,iv:N1mL9Ge20/W3JIr1YLLMDltKQrVCoPjMsKezSwI6dmg=,tag:cf+9ys++HF6+PrwsKSxyDw==,type:str]
    pgp:
        - created_at: "2026-02-03T14:15:37Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwSeVs53q4TjAQ//TuYSG+nZTCfKSEQ+sygmr8EqksdD1VJpddw6rSOfZ5sV
            gw/HQUxwR09HkVFaXbPkL/fDvJTtNZlcjHJQQ43+zAmPAiZnkSh2ytU8ah9j1DKj
            IotdZY1StSsjlvGZYm9ZG3eAU6T4zvjNuxoleSt0Rk/4g6su8UAenp0YMFApAc4o
            nqZV61fzhTB+z/Wq4T1WtbaGg5Cdsl9J0SRp5D2Jjf2g+JjmiYoI7RfSY9cu4c38
            QKJxQh1C3soXSFDndmizxZJBJ0yzefa3zxWAZozVroxIUX+XrxDbZia/rlHc5mmp
            7tjRgowwzLMVvyzbdcuLlV65PN9hRyg927yUvYkxgjLMs6/VkoDj+N487MPu1wga
            uORzEjpD97mbzatc4oIf8k7uHcPFyPvQlSm/PiojuFYVc903GMrC+n+DooGKi+7d
            j/SsYzIak333EWZ0AX3y3l+b+O+d0R1y6uI3Te4zQwGzBmgqop8LrnOBqoMsxzBQ
            97USK1M6ZJ9gPROAJ0I/6Jk4iTsKiXs9zNODD+Qx93DmfvXfLZeB9XheWXIhvt+2
            JTYI5cJoVq4GauoAgWENGlJhYDlSIWKY7dqHvznGa4rlKsw2LV3MPg5fVtzraxxf
            ZVysEUBjJpJzZUOQzlNaH1w4GJ5zUDgjZOWzbB2EJ3Qet1C3idOUmIJ1jy0IuiTU
            ZgEJAhAmKjU0JfdQLMu6zhG4IpH64bWNAhwRd+myhhOH0YHlCoZt9+vjFfT7Da4l
            BzWiwcu6kNsX4UKcVYDhC+iejHAWDRUmOiA/Miu+0wSJdUc2YaP08QB59Hi0dtGY
            /8PzhFrPqQ==
            =IkQ7
            -----END PGP MESSAGE-----
          fp: EA65B90F135CF8C5E331DA40C87A0BEB390664D3
        - created_at: "2026-02-03T14:15:37Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D2q685yeOqr8SAQdAHaWAAyxW3iefad4ByrHT9dTquM//VlIsJyf4HJnCJzEw
            OQr4pnKJ0ob49rawiQLRsPR428tVV1MBk6YZ/3CFuR3AN7lUCDNvMYsX9wP50Xme
            1GYBCQIQfAI8iSwjcd9vZVVx+vic2LrM34REYnlk32UFYFpnMLpN95YPq8mYNyGa
            TrKIFWPX+6Jd8xGtO7pfhzg0rs/Rf1DFq2J1Ad7VfGWshY3qXmowVpPxBghFLn37
            f6PNw3mPfRE=
            =T41i
            -----END PGP MESSAGE-----
          fp: D25B7C5D2B5FE33FAB3EBF4BCB6E270ECA40D3A0
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
