---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-certificate
  namespace: harbor-registry
spec:
  secretName: harbor-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false

  dnsNames:
    - harbor.golebiowski.dev

  usages:
    - digital signature
    - key encipherment

  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
