apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: harbor-registry
  namespace: harbor-registry
spec:
  type: "oci"
  interval: 5m0s
  url: oci://registry-1.docker.io/bitnamicharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor-registry
  namespace: harbor-registry
spec:
  interval: 5m
  chart:
    spec:
      chart: harbor
      version: "<25.0.0"
      sourceRef:
        kind: HelmRepository
        name: harbor-registry
        namespace: harbor-registry
      interval: 1m
  values:
    global:
      defaultStorageClass: local-path
    clusterDomain: cluster.local
    externalURL: https://harbor.golebiowski.dev
    persistence:
      persistentVolumeClaim:
        registry:
          size: 100Gi
    core:
      updateStrategy:
        type: Recreate
    jobservice:
      updateStrategy:
        type: Recreate
    registry:
      updateStrategy:
        type: Recreate
    exposureType: ingress
    ingress:
      enabled: true
      selfSigned: true
      core:
        ingressClassName: nginx
        hostname: harbor.golebiowski.dev
        tls: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
  valuesFrom:
    - kind: Secret
      name: harbor-secrets
