site_name: Anton The Cluster
theme:
  name: material
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.footer
    - search.suggest
    - content.code.copy
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gregg127/anton
plugins:
  - search
copyright: Copyright &copy; 2025 Grzegorz Gołębiowski
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.details
